#!/bin/bash

set -e

version=$1

cat <<EOF > setup.py
from distutils.core import setup 
setup(
      name = 'greentranslator',
      packages = [ 'greentranslator' ], # this must be the same as the name above
      package_dir={ 'greentranslator' : 'greentranslator' },
      package_data={ 'greentranslator' : [ 'query/*.sparql' ]},
      version = '$version',
      description = 'Green Team BioMedical Data Translator',
      author = 'Steve Cox',
      author_email = 'scox@renci.org',
      include_package_data=True,
      url = 'https://github.com/ResearchSoftwareInstitute/greendatatranslator',
      download_url = 'https://github.com/ResearchSoftwareInstitute/greendatatranslator/archive/$version.tar.gz',
      keywords = [ 'biomedical', 'environmental', 'exposure', 'clinical' ],
      classifiers = [ ],
    )
EOF

if [ -z "$version" ]; then
    echo version parameter is required
    exit 0
fi

publish () {
    if [ -z "$( git tag | grep $version )" ]; then
	git commit -am "api version $version"
	git push origin master
	
	git tag $version -m "publishing version $version"
	git push --tags origin master
	
	python setup.py register -r pypitest
	python setup.py sdist upload -r pypitest
	python setup.py register -r pypi
	python setup.py sdist upload -r pypi
    fi
    if [ "$( pip freeze | grep greentranslator | grep -c greentranslator)" -gt 0 ]; then
	python -m pip --no-cache-dir uninstall -y greentranslator
    fi
    python -m pip --no-cache-dir install greentranslator==$version

 
    cd ..
    cat <<EOF> test.py
from greentranslator.api import GreenTranslator
translator = GreenTranslator()
exposure = translator.get_exposure_by_area (exposure_type = 'pm25',
                                            latitude      = '',
                                            longitude     = '',
                                            radius        = '0')
print ("Exposure: {}".format (exposure))
EOF
    python test.py

#    rm test.py
}


publish $*
